console.log ("Hi, I'm in console screen");
var first_name = "Sanaya";
var last_name = "Shetty";
console.log (last_name);
var full_name = first_name.concat (last_name);
console.log (full_name);
var name_length = full_name.length;
console.log (name_length); 
var name_one = "I am Sanaya Shetty";
var replace_name = name_one.replace ("Sanaya", "Samaira");
console.log (replace_name);
var capital_name = "SANAYA";
var Lcase = capital_name.toLowerCase();
console.log (Lcase);
var capital_name = "samaira";
var Ucase = capital_name.toUpperCase();
console.log (Ucase);
var square_root = Math.sqrt (16);
console.log (square_root);
var maxium_number = Math.max(10, 50);
console.log  (maxium_number);
var min_number = Math.min(10, 50);
console.log  (min_number);
var power_eg = Math.pow (4, 2);
console.log (power_eg);
